CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  "name" VarChar(45) NOT NULL,
  "password" TEXT NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  "email" TEXT NOT NULL
);

CREATE TABLE tokens(
  value CHAR(128) PRIMARY KEY,
  ip VarChar(30) NOT NULL,
  user_id INT NOT NULL
);

-- Could add a description and images, but meh.
CREATE TABLE products(
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  -- Categories list will generated by a view instead.
  category TEXT NOT NULL,
  -- same thing...
  manufacturer TEXT NOT NULL,
  CHECK (quantity >= 0),
  CHECK (price > 0)
);

CREATE TABLE receipts(
  id SERIAL PRIMARY KEY,
  stamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  total NUMERIC(10, 2) NOT NULL,
  subtotal NUMERIC(10, 2) NOT NULL,
  user_id INT NOT NULL REFERENCES users(id),
  -- e.g., google wallet, paypal, credit
  method VARCHAR(45) NOT NULL,
  CHECK (subtotal < total),
  CHECK (subtotal > 0)
);

CREATE TABLE purchases(
  id SERIAL PRIMARY KEY,
  --stamp TIMESTAMP NOT NULL,
  --user_id INT NOT NULL REFERENCES users(id),
  receipt_id INT NOT NULL REFERENCES receipts(id),
  product_id INT NOT NULL REFERENCES products(id),
  quantity INT NOT NULL
);



-- Products in cart
CREATE TABLE held_products(
  id SERIAL PRIMARY KEY,
  quantity INT NOT NULL,
  user_id INT NOT NULL REFERENCES users(id),
  product_id INT NOT NULL REFERENCES products(id)
);
